# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logdet <- function(M) {
    .Call(`_mixglm_logdet`, M)
}

log_like_glm_cpp <- function(y_k, X_k, beta_k, W_k, alpha, sigma2, family) {
    .Call(`_mixglm_log_like_glm_cpp`, y_k, X_k, beta_k, W_k, alpha, sigma2, family)
}

complete_log_like_glm_cpp <- function(y, X, W, beta, alpha, family, sigma2, sigma_fixed, sample_size, K) {
    .Call(`_mixglm_complete_log_like_glm_cpp`, y, X, W, beta, alpha, family, sigma2, sigma_fixed, sample_size, K)
}

gr_theta_k_binomial_cpp <- function(y_k, X_k, W_k, beta_k, alpha) {
    .Call(`_mixglm_gr_theta_k_binomial_cpp`, y_k, X_k, W_k, beta_k, alpha)
}

gr_theta_k_gaussian_cpp <- function(y_k, X_k, W_k, beta_k, alpha, R_k, sigma_k) {
    .Call(`_mixglm_gr_theta_k_gaussian_cpp`, y_k, X_k, W_k, beta_k, alpha, R_k, sigma_k)
}

gr_theta_cpp <- function(y, X, W, family, beta, alpha, sigma, sigma_fixed, sample_size, K, p_x, p_w, nu, Lamb, kappa) {
    .Call(`_mixglm_gr_theta_cpp`, y, X, W, family, beta, alpha, sigma, sigma_fixed, sample_size, K, p_x, p_w, nu, Lamb, kappa)
}

